osx_image: xcode10.2
language: swift
xcode_workspace: MultiProgressView.xcworkspace
xcode_scheme: MultiProgressViewTests
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone SE

#Codecov
script:
  - xcodebuild -scheme MultiProgressViewTests -workspace MultiProgressView.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=12.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
